  name: Deployment to Production
  on:
    push:
      branches:
        - master
  jobs:
    gh-pages-deploy:
      name: Deploying to Production
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v3
            with:
              persist-credentials: false
          - uses: actions/setup-node@v2
            with:
              node-version: '16.16.0'
          - name: Setup SSH Keys and known_hosts
            env:
              SSH_AUTH_SOCK: /tmp/ssh_agent.sock
            run: ssh-agent -a $SSH_AUTH_SOCK > /dev/null && ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          - name: Install packages
            env:
              SSH_AUTH_SOCK: /tmp/ssh_agent.sock
            run: cd mehmetbarispolat.dev && npm i npm-run-all
          - name: Deploy
            env:
              SSH_AUTH_SOCK: /tmp/ssh_agent.sock
            run: cd mehmetbarispolat.dev && npm run deploy