  name: Deployment to Production
  on:
    push:
      branches:
        - master
  jobs:
    gh-pages-deploy:
      name: Deploying to Production
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
            with:
              persist-credentials: false
          - uses: actions/setup-node@v2
            with:
              node-version: 12.x
          - name: Install packages
            run: cd mehmetbarispolat.dev && npm i
          - name: Set Creds
            run: git config user.name "mehmetbarispolat" && git config user.email "mehmetbarispolat@gmail.com"
          - name: Deploy
            run: npm run deploy